# Site settings
name: Kem Nguyen-Le
title: Kem Nguyen-Le | INFO PhD
description: INFO PhD student at University of Maryland.
url: https://kemnguyenle.github.io/
baseurl: ''
email: nlpa@umd.edu
# cover: 
logo: https://bchiang7.github.io/img/emojis/technologist.png
# resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:nlpa@umd.edu
  - title: X
    url: https://x.com/KemNguyenLe
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  # #   url: http://codepen.io/bchiang7
  # - title: github
  #   url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/kem-nguyen-le/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
